
name: ci
on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    - cron: '0 1 * * 0'

# https://docs.docker.com/build/ci/github-actions/share-image-jobs/
# just using caches instead of artifact upload.
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      -
        name: Create docker cache folder
        run: mkdir -p /tmp/docker
      -
        name: Restore docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('builder.Dockerfile') }}
      -
        name: Build docker builder-image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: builder.Dockerfile
          tags: kconfig-root-demo-builder:latest
          outputs: type=docker,dest=/tmp/docker/${{ runner.os }}-builder-image.tar

  build:
    runs-on: ubuntu-latest
    needs: docker-build
    strategy:
      fail-fast: false
      matrix:
        tuple:
          - { root: 'app_00_replace_root', invoke: 'build' }
          - { root: 'app_01_rsource',      invoke: 'build' }
          - { root: 'app_02_modules',      invoke: 'build' }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      -
        name: Restore docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('builder.Dockerfile') }}
      -
        name: Load image
        run: |
          docker load --input /tmp/docker/${{ runner.os }}-builder-image.tar
          docker image ls -a
      -
        name: Build
        run: |
          docker run \
            --rm \
            --platform linux/amd64 \
            --workdir /workspaces/kconfig-root-demo \
            -v ${{ github.workspace }}:/workspaces/kconfig-root-demo \
            kconfig-root-demo-builder:latest \
            /bin/bash -c "cd ${{ matrix.tuple.root }} && invoke ${{ matrix.tuple.invoke }}"
